title: ERIM RDM Toolbox
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: ERIM RDM Toolbox
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: "ERIM Research Data Management (RDM) Toolbox for Researchers at Erasmus University Rotterdam"
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@1.23.0

exclude:
  - README.md
  - vendor

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: main
  - scope:
      path: "pages/data_life_cycle"
    values:
      type: data_life_cycle

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-github-metadata
  - webrick
